Fix Int overflow
Error: Failed to parse the result returned by cloudflare

Caused by:
    0: error decoding response body: invalid value: integer `3600`, expected u8 at line 1 column 1131
    1: invalid value: integer `3600`, expected u8 at line 1 column 1131